# Generated by Django 4.2.4 on 2023-08-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delete_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='modify_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
