# Generated by Django 4.2.4 on 2023-08-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_delete_timestamp_product_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='akbar', max_length=20),
            preserve_default=False,
        ),
    ]
